"""sync models

Revision ID: d6ead0fe7e6e
Revises: 82977ebeae62
Create Date: 2025-12-30 16:35:54.219942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ead0fe7e6e'
down_revision: Union[str, Sequence[str], None] = '82977ebeae62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('content', sa.Column('title', sa.String(), nullable=False))
    op.add_column('content', sa.Column('content', sa.String(), nullable=False))
    op.add_column('content', sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False))
    op.add_column('content', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('content', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'owner_id')
    op.drop_column('content', 'created_at')
    op.drop_column('content', 'published')
    op.drop_column('content', 'content')
    op.drop_column('content', 'title')
    op.drop_table('votes')
    op.drop_table('users')
    # ### end Alembic commands ###
